baseURL: "https://sloaneblog.netlify.app"
languageCode: "en-uk"
title: "Syntax & Substance"
theme: "stack"

outputs:
  home:
    - HTML
    - RSS
    - JSON

outputFormats:
  JSON:
    baseName: index
    isPlainText: true
    mediaType: application/json
    notAlternative: true

params:
  search:
    enable: true
    type: basic
  description: "My personal blog about technology, life, and interesting thoughts"
  favicon: "/images/Olivia.png"
  colorScheme:
    default: "custom"
  mainSections: ["posts", "tutorials", "projects"]
  emoji: "❤️"
  Article:
    author: "Samuel Jnr"
    share_buttons: true
    categories: true
    tags: true
    math: true
    toc: true
  sidebar:
    subtitle: "Olivia is on fire"
    enabled: true
    position: right
    widgets:
      - toc
      - search
      - recentPosts
      - categories
      - tags
  comments:
    enabled: true
    provider: giscus
    giscus:
      repo: "Sloane-J/SloaneBlog"
      repoID: "R_kgDONXOl1A"
      category: "General"
      categoryID: "DIC_kwDONXOl1M4Ckxju"
      mapping: "pathname"
      reactionsEnabled: 1
      emitMetadata: 0
      lang: "en"
      theme: "preferred_color_scheme"
  widgets:
    homepage:
      - type: search
      - type: categories
        params:
          limit: 5
      - type: tag-cloud
    page:
      - type: search
      

  customCSS: "/css/custom.css"

  customColors:
    primary: "#3D52A0"
    secondary: "#7091E6"
    background: "#F0F4F8"
    text: "#1A2B3C"
    link: "#3D52A0"

  enableDarkModeToggle: true
  social:
    - name: GitHub
      url: "https://github.com/Sloane-J"
    - name: Twitter
      url: "https://twitter.com/sloane_jnr"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
      params:
        icon: home
    - identifier: posts
      name: Posts
      url: /posts
      weight: 2
      params:
        icon: archives
    - identifier: tutorials
      name: Tutorials
      url: /tutorials
      weight: 3
      params:
        icon: school
    - identifier: projects
      name: Projects
      url: /projects
      weight: 4
      params:
        icon: code
    - identifier: about
      name: About
      url: /about
      weight: 5
      params:
        icon: user
    - identifier: search
      name: Search
      url: /search
      weight: 6
      params:
        icon: search

taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"
  genre: genres

permalinks:
  post: "/:year/:month/:day/:slug/"

markup:
  defaultMarkdownHandler: goldmark

enableGitinfo: true
