baseURL: "https://intheloop-blog.netlify.app/"
theme: "stack"
languageCode: "en-GB"
title: "InTheLoop"

outputs:
  home:
    - HTML
    - RSS
    - JSON

outputFormats:
  JSON:
    baseName: index
    isPlainText: true
    mediaType: application/json
    notAlternative: true

mainSections:
  - posts
  - technology
  - deals
  - trailers
  - search

imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart

enableRobotsTXT: true
canonifyURLs: false

params:
  contact:
    email: samueldorkeyjr@gmail.com
    phone: +233 257774919
  pagination:
    pagerSize: 6
  logo: "/images/avatar.webp"
  cover:
    enable: true
  content:
    enable: true
  search:
    enable: true
    type: basic
  description: "My personal blog about technology, life, and interesting thoughts"
  favicon: "/images/avatar.webp"
  emoji: "❤️"
  social:
  - name: Github
    url: "https://github.com/Sloane-J"
  - name: Twitter
    url: "https://twitter.com/sloane_jnr"

  enableEmoji: true

  widgets:
    homepage:
      - type: search
      - type: categories
        params:
          limit: 6
      - type: tag-cloud
    page:
      - type: search
      - type: categories
        params:
          limit: 6
      - type: tag-cloud

  sidebar:
    subtitle: "Insights on Technology, Science, and More"
    enabled: true
    position: right

  Article:
    author: "Samuel Jnr"
    share_buttons: true
    categories: true
    tags: true
    math: true
    toc: true

  comments:
    enabled: true
    provider: giscus
    giscus:
      repo: "Sloane-J/SloaneBlog"
      repoID: "R_kgDONXOl1A"
      category: "General"
      categoryID: "DIC_kwDONXOl1M4Ckxju"
      mapping: "pathname"
      reactionsEnabled: 1
      emitMetadata: 0
      lang: "en"
      theme: "preferred_color_scheme"

  schema:
    name: "Sloane's Blog"
    description: "Insights on Technology, Science, and More"
    url: "https://intheloop-blog.netlify.app/"
    logo: "https://intheloop-blog.netlify.app/images/avatar.webp"
    author:
      name: "Samuel D. Jnr"
      jobTitle: "Tech Blogger"
      description: "Writer and technology enthusiast sharing insights on science and technology"



menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
      params:
        icon: home
    - identifier: posts
      name: News
      url: /posts
      weight: 2
      params:
        icon: news
    - identifier: technology
      name: Technology
      url: /technology
      weight: 5
      params:
        icon: augmented-reality
    - identifier: deals
      name: Deals
      url: /deals
      weight: 6
      params:
        icon: shopping-cart
    - identifier: about
      name: About
      url: /about
      weight: 7
      params:
        icon: user
    - identifier: trailers
      name: Trailers
      url: /trailers
      weight: 8
      params:
        icon: movie
    - identifier: search
      name: Search
      url: /search
      weight: 9
      params:
        icon: search

taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"
  genre: "genres"

permalinks:
  post: "/:year/:month/:day/:slug/"

markup:
  goldmark:
    renderer:
      unsafe: true

enableGitinfo: true

sitemap:
  changeFreq: weekly
  disable: false
  filename: sitemap.xml
  priority: -1

minify: 
  enable: true


frontmatter:
  date:
  - date
  - publishdate
  - pubdate
  - published
  - lastmod
  - modified
  expiryDate:
  - expirydate
  - unpublishdate
  lastmod:
  - :git
  - lastmod
  - modified
  - date
  - publishdate
  - pubdate
  - published
  publishDate:
  - publishdate
  - pubdate
  - published
  - date