[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.139.2"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
    Referrer-Policy = "no-referrer-when-downgrade"